# CMake info
set(CMAKE_MIN_VERSION 3.5.0)

# Engine info
set(ENGINE_NAME Wireframe-Engine)

set(ENGINE_VERSION_MAJOR 0)
set(ENGINE_VERSION_MINOR 1)
set(ENGINE_VERSION_PATCH 0)

# Test project info
set(TEST_PROJECT_NAME Test-Project)

set(TEST_PROJECT_VERSION_MAJOR 1)
set(TEST_PROJECT_VERSION_MINOR 0)
set(TEST_PROJECT_VERSION_PATCH 0)
