#include <BuildInfo.hpp>

#ifdef WFE_PLATFORM_WINDOWS

#include "Internal.hpp"
#include "Platform/Input.hpp"
#include "Platform/KeyCode.hpp"

namespace wfe {
	// Key code converter
	KeyCode VKToKeyCode(WPARAM wParam) {
		switch(wParam) {
		case VK_LBUTTON:
			return KEY_LEFT_MBUTTON;
		case VK_RBUTTON:
			return KEY_RIGHT_MBUTTON;
		case VK_MBUTTON:
			return KEY_MIDDLE_MBUTTON;
		case VK_XBUTTON1:
			return KEY_X1_MBUTTON;
		case VK_XBUTTON2:
			return KEY_X2_MBUTTON;
		case VK_BACK:
			return KEY_BACKSPACE;
		case VK_TAB:
			return KEY_TAB;
		case VK_CLEAR:
			return KEY_CLEAR;
		case VK_RETURN:
			return KEY_ENTER;
		case VK_SHIFT:
			return KEY_SHIFT;
		case VK_CONTROL:
			return KEY_CONTROL;
		case VK_MENU:
			return KEY_ALT;
		case VK_PAUSE:
			return KEY_PAUSE;
		case VK_CAPITAL:
			return KEY_CAPS_LOCK;
		case VK_ESCAPE:
			return KEY_ESCAPE;
		case VK_SPACE:
			return KEY_SPACE;
		case VK_INSERT:
			return KEY_INSERT;
		case VK_DELETE:
			return KEY_DELETE;
		case VK_HOME:
			return KEY_HOME;
		case VK_END:
			return KEY_END;
		case VK_PRIOR:
			return KEY_PAGE_UP;
		case VK_NEXT:
			return KEY_PAGE_DOWN;
		case VK_LEFT:
			return KEY_LEFT_ARROW;
		case VK_UP:
			return KEY_UP_ARROW;
		case VK_DOWN:
			return KEY_DOWN_ARROW;
		case VK_SNAPSHOT:
			return KEY_PRINT_SCREEN;
		case 0x30:
			return KEY_0;
		case 0x31:
			return KEY_1;
		case 0x32:
			return KEY_2;
		case 0x33:
			return KEY_3;
		case 0x34:
			return KEY_4;
		case 0x35:
			return KEY_5;
		case 0x36:
			return KEY_6;
		case 0x37:
			return KEY_7;
		case 0x38:
			return KEY_8;
		case 0x39:
			return KEY_9;
		case 0x41:
			return KEY_A;
		case 0x42:
			return KEY_B;
		case 0x43:
			return KEY_C;
		case 0x44:
			return KEY_D;
		case 0x45:
			return KEY_E;
		case 0x46:
			return KEY_F;
		case 0x47:
			return KEY_G;
		case 0x48:
			return KEY_H;
		case 0x49:
			return KEY_I;
		case 0x4a:
			return KEY_J;
		case 0x4b:
			return KEY_K;
		case 0x4c:
			return KEY_L;
		case 0x4d:
			return KEY_M;
		case 0x4e:
			return KEY_N;
		case 0x4f:
			return KEY_O;
		case 0x50:
			return KEY_P;
		case 0x51:
			return KEY_Q;
		case 0x52:
			return KEY_R;
		case 0x53:
			return KEY_S;
		case 0x54:
			return KEY_T;
		case 0x55:
			return KEY_U;
		case 0x56:
			return KEY_V;
		case 0x57:
			return KEY_W;
		case 0x58:
			return KEY_X;
		case 0x59:
			return KEY_Y;
		case 0x5A:
			return KEY_Z;
		case VK_LWIN:
			return KEY_LWIN;
		case VK_RWIN:
			return KEY_RWIN;
		case VK_NUMPAD0:
			return KEY_NUMPAD0;
		case VK_NUMPAD1:
			return KEY_NUMPAD1;
		case VK_NUMPAD2:
			return KEY_NUMPAD2;
		case VK_NUMPAD3:
			return KEY_NUMPAD3;
		case VK_NUMPAD4:
			return KEY_NUMPAD4;
		case VK_NUMPAD5:
			return KEY_NUMPAD5;
		case VK_NUMPAD6:
			return KEY_NUMPAD6;
		case VK_NUMPAD7:
			return KEY_NUMPAD7;
		case VK_NUMPAD8:
			return KEY_NUMPAD8;
		case VK_NUMPAD9:
			return KEY_NUMPAD9;
		case VK_ADD:
			return KEY_NUMPAD_ADD;
		case VK_SUBTRACT:
			return KEY_NUMPAD_SUBTRACT;
		case VK_MULTIPLY:
			return KEY_NUMPAD_MULTIPLY;
		case VK_DIVIDE:
			return KEY_NUMPAD_DIVIDE;
		case VK_SEPARATOR:
			return KEY_NUMPAD_SEPARATOR;
		case VK_DECIMAL:
			return KEY_NUMPAD_DECIMAL;
		case VK_F1:
			return KEY_F1;
		case VK_F2:
			return KEY_F2;
		case VK_F3:
			return KEY_F3;
		case VK_F4:
			return KEY_F4;
		case VK_F5:
			return KEY_F5;
		case VK_F6:
			return KEY_F6;
		case VK_F7:
			return KEY_F7;
		case VK_F8:
			return KEY_F8;
		case VK_F9:
			return KEY_F9;
		case VK_F10:
			return KEY_F10;
		case VK_F11:
			return KEY_F11;
		case VK_F12:
			return KEY_F12;
		case VK_F13:
			return KEY_F13;
		case VK_F14:
			return KEY_F14;
		case VK_F15:
			return KEY_F15;
		case VK_F16:
			return KEY_F16;
		case VK_F17:
			return KEY_F17;
		case VK_F18:
			return KEY_F18;
		case VK_F19:
			return KEY_F19;
		case VK_F20:
			return KEY_F20;
		case VK_F21:
			return KEY_F21;
		case VK_F22:
			return KEY_F22;
		case VK_F23:
			return KEY_F23;
		case VK_F24:
			return KEY_F24;
		case VK_NUMLOCK:
			return KEY_NUM_LOCK;
		case VK_SCROLL:
			return KEY_SCROLL_LOCK;
		case VK_LSHIFT:
			return KEY_LSHIFT;
		case VK_RSHIFT:
			return KEY_RSHIFT;
		case VK_LCONTROL:
			return KEY_LCONTROL;
		case VK_RCONTROL:
			return KEY_RCONTROL;
		case VK_LMENU:
			return KEY_LALT;
		case VK_RMENU:
			return KEY_RALT;
		case VK_BROWSER_BACK:
			return KEY_BROWSER_BACK;
		case VK_BROWSER_FORWARD:
			return KEY_BROWSER_FORWARD;
		case VK_BROWSER_REFRESH:
			return KEY_BROWSER_REFRESH;
		case VK_BROWSER_STOP:
			return KEY_BROWSER_STOP;
		case VK_BROWSER_FAVORITES:
			return KEY_BROWSER_FAVORITES;
		case VK_BROWSER_HOME:
			return KEY_BROWSER_HOME;
		case VK_VOLUME_MUTE:
			return KEY_VOLUME_MUTE;
		case VK_VOLUME_DOWN:
			return KEY_VOLUME_DOWN;
		case VK_VOLUME_UP:
			return KEY_VOLUME_UP;
		case VK_MEDIA_NEXT_TRACK:
			return KEY_MEDIA_NEXT;
		case VK_MEDIA_PREV_TRACK:
			return KEY_MEDIA_PREV;
		case VK_MEDIA_STOP:
			return KEY_MEDIA_STOP;
		case VK_MEDIA_PLAY_PAUSE:
			return KEY_MEDIA_PLAY_PAUSE;
		case VK_OEM_1:
			return KEY_SEMICOLON;
		case VK_OEM_PLUS:
			return KEY_EQUAL;
		case VK_OEM_MINUS:
			return KEY_MINUS;
		case VK_OEM_COMMA:
			return KEY_COMMA;
		case VK_OEM_PERIOD:
			return KEY_PERIOD;
		case VK_OEM_2:
			return KEY_SLASH;
		case VK_OEM_3:
			return KEY_BACKTICK;
		case VK_OEM_4:
			return KEY_OPEN_SQR_PARENTHESIS;
		case VK_OEM_6:
			return KEY_CLOSED_SQR_PARENTHESIS;
		case VK_OEM_5:
			return KEY_BACKSLASH;
		case VK_OEM_7:
			return KEY_QUOTES;
		}

		return KEY_NONE;
	}
}

#endif