#pragma once

// Project info
#define WFE_PROJECT_NAME "Unnamed-Project"

#define WFE_PROJECT_VERSION_MAJOR 1
#define WFE_PROJECT_VERSION_MINOR 0
#define WFE_PROJECT_VERSION_PATCH 0
#define WFE_PROJECT_VERSION_TWEAK 0

// Engine info
#define WFE_ENGINE_NAME "Wireframe-Engine"

#define WFE_ENGINE_VERSION_MAJOR 0
#define WFE_ENGINE_VERSION_MINOR 1
#define WFE_ENGINE_VERSION_PATCH 0
#define WFE_ENGINE_VERSION_TWEAK 0
