#pragma once

#include "Assets/Rendering/Core/ImageCubemap.hpp"
#include "Assets/Rendering/Core/ImageTexture.hpp"
#include "Assets/Rendering/Main/MaterialCollection.hpp"
#include "Assets/Rendering/Main/RenderObject.hpp"

#include "Core/Assets/Asset.hpp"
#include "Core/Assets/AssetDirectory.hpp"
#include "Core/Assets/AssetManager.hpp"
#include "Core/Assets/AssetType.hpp"
#include "Core/ECS/ComponentList.hpp"
#include "Core/ECS/ComponentType.hpp"
#include "Core/ECS/EntityManager.hpp"
#include "Core/ECS/Transform.hpp"
#include "Core/Math/General/MathUtils.hpp"
#include "Core/Math/General/MatUtils.hpp"
#include "Core/Math/General/QuatUtils.hpp"
#include "Core/Math/General/VecUtils.hpp"
#include "Core/Math/Geometry/Geometry2d.hpp"
#include "Core/Math/Templates/Mat.hpp"
#include "Core/Math/Templates/Quat.hpp"
#include "Core/Math/Templates/Vec.hpp"
#include "Core/Math/Templates/Vec2.hpp"
#include "Core/Math/Templates/Vec3.hpp"
#include "Core/Math/Templates/Vec4.hpp"
#include "Core/Memory/Allocator.hpp"
#include "Core/Memory/VirtualMemory.hpp"
#include "Core/Parsers/Image/ImageParser.hpp"
#include "Core/Parsers/Image/PNGParser.hpp"
#include "Core/Parsers/Image/TGAParser.hpp"
#include "Core/Parsers/Utils/JSONParser.hpp"
#include "Core/Types/BuildInfo.hpp"
#include "Core/Types/Defines.hpp"
#include "Core/Utils/BinaryIO.hpp"
#include "Core/Utils/Event.hpp"
#include "Core/Utils/Logger.hpp"
#include "Core/Utils/UpdateClock.hpp"

#include "Graphics/Main/Components/MeshRenderer.hpp"
#include "Graphics/Main/Components/SceneLight.hpp"
#include "Graphics/Main/Instance/MainPipeline.hpp"
#include "Graphics/Main/Resources/Material.hpp"
#include "Graphics/Main/Resources/RenderMesh.hpp"
#include "Graphics/Skybox/Instance/SkyboxPipeline.hpp"
#include "Graphics/Skybox/Resources/Skybox.hpp"
#include "Graphics/EngineGraphics.hpp"
#include "Graphics/GraphicsSystem.hpp"

#include "Info/EngineInfo.hpp"

#include "Main/Program.hpp"

#include "Platform/Input.hpp"
#include "Platform/Window.hpp"

#include "Vulkan/API/VulkanStructSize.hpp"
#include "Vulkan/Instance/VulkanAllocator.hpp"
#include "Vulkan/Instance/VulkanCommandPool.hpp"
#include "Vulkan/Instance/VulkanDevice.hpp"
#include "Vulkan/Instance/VulkanInstance.hpp"
#include "Vulkan/Instance/VulkanPipelineCache.hpp"
#include "Vulkan/Instance/VulkanSurface.hpp"
#include "Vulkan/Instance/VulkanSwapChain.hpp"
#include "Vulkan/Loader/VulkanLoader.hpp"
#include "Vulkan/Resources/VulkanBuffer.hpp"
#include "Vulkan/Resources/VulkanCommand.hpp"
#include "Vulkan/Resources/VulkanImage.hpp"
#include "Vulkan/VulkanRenderer.hpp"