#pragma once

#include "Assets/General/ImageTexture.hpp"
#include "Assets/Rendering/Shader.hpp"

#include "Core/Assets/Asset.hpp"
#include "Core/Assets/AssetManager.hpp"
#include "Core/Assets/AssetType.hpp"
#include "Core/ECS/ComponentList.hpp"
#include "Core/ECS/ComponentType.hpp"
#include "Core/ECS/EntityManager.hpp"
#include "Core/ECS/Transform.hpp"
#include "Core/Math/Matrix4x4.hpp"
#include "Core/Math/Quaternion.hpp"
#include "Core/Math/Vector2.hpp"
#include "Core/Math/Vector3.hpp"
#include "Core/Math/Vector4.hpp"
#include "Core/Memory/Allocator.hpp"
#include "Core/Memory/VirtualMemory.hpp"
#include "Core/Parsers/ImageParser.hpp"
#include "Core/Parsers/WFEONParser.hpp"
#include "Core/Types/BuildInfo.hpp"
#include "Core/Types/Defines.hpp"
#include "Core/Utils/Event.hpp"
#include "Core/Utils/Logger.hpp"

#include "Info/EngineInfo.hpp"

#include "Main/Program.hpp"

#include "Platform/Input.hpp"
#include "Platform/Window.hpp"

#include "Vulkan/API/VulkanStructSize.hpp"
#include "Vulkan/Instance/VulkanAllocator.hpp"
#include "Vulkan/Instance/VulkanDevice.hpp"
#include "Vulkan/Instance/VulkanInstance.hpp"
#include "Vulkan/Instance/VulkanSurface.hpp"
#include "Vulkan/Instance/VulkanSwapChain.hpp"
#include "Vulkan/Loader/VulkanLoader.hpp"
#include "Vulkan/VulkanRenderer.hpp"